### ISSUE TITLE
Not using tree sitter grammars

### ISSUE THREAD

**Issue by dflock** [hedefalk/atom-vue#102]
The current atom-vue isn't a tree-sitter grammar and doesn't use tree sitter grammars for JavaScript `<script>` parts either.

**Comment by aidistan** [comment]
@dflock Thanks for the proposal. We shall work on it.

**Comment by foundryspatial-duncan** [comment]
Is this why object keys changed color recently? (Maybe when Atom started using tree sitter stuff?)
Right now, my object keys are all green, as if they were a string, where they used to be red.

![Screenshot from 2019-09-23 11-20-25](https://user-images.githubusercontent.com/13056053/65451565-4c195c80-ddf4-11e9-9965-662924c9cc2f.png)

**Comment by aidistan** [comment]
@foundryspatial-duncan Yes, it is. Since Atom used `tree-sitter` as the default parser from 1.32.

**Comment by jonboiser** [comment]
I've added a Tree-Sitter grammar on [my fork of this library](https://github.com/jonboiser/atom-vue/tree/tree-sitter), which relies on the
[tree-sitter-vue parser](https://github.com/ikatyang/tree-sitter-vue) that was created recently.

If people would like to check it out and maybe even fill in some of the gaps, I would be grateful. My grammar is pretty minimalistic, and I've only tested it on the Dracula theme.

I still need to add syntax highlighting for the '<style>' tag, which is limited to  only CSS (so might work with SCSS too) because there doesn't seem to be tree-sitter support for other CSS pre-processors.

**Comment by confused-Techie** [comment]
@dflock as this package is now in mostly maintenance mode, I'm going to venture to suggest this feature may not be implemented for the time being. It's of course very appreciated that you reached out with the feature request, but I'm not aware of any efforts being made to additionally offer a Tree-Sitter grammar. That is unless @jonboiser would want to draft a PR with their forked changes back here and get those merged in, which would be fantastic!

Otherwise, while appreciated, I'll go ahead and close this issue for now, as this feature does not seem to be planned.
