### ISSUE TITLE
Null Propagation operator support

### ISSUE THREAD

**Issue by DutchGerman** [hedefalk/atom-vue#109]
When using the Null Propagation operator ( ?. ) in a file it breaks the syntax highlighting.

When you use it in the template:
![grafik](https://user-images.githubusercontent.com/60694691/88782253-a52cec00-d18d-11ea-926c-3a6f7d6d3769.png)

When you use it in the script:
![grafik](https://user-images.githubusercontent.com/60694691/88782372-cd1c4f80-d18d-11ea-9662-5fa4bb4deb43.png)

**Comment by confused-Techie** [comment]
Looking into this, this seems that the issue stems from the fact that Atom previously did not support optional chaining operators in JavaScript. That's why as reported by others using `language-babel` instead would resolve the issue.

This was fixed in Pulsar:
* In [TextMate Grammars](https://github.com/pulsar-edit/pulsar/pull/79)

Testing now, with the latest version of Pulsar gives me the following: (When trying to duplicate the shown snippet of text)

![image](https://github.com/hedefalk/atom-vue/assets/26921489/0a017ff7-3dc4-47ca-b8a5-40ce7a450f60)

So as long as you are up to date on Pulsar, this issue should be resolved.
