### ISSUE TITLE
<script> and <style> not being highlighted when the cursor is inside the tags

### ISSUE THREAD

**Issue by zhaolinlau** [hedefalk/atom-vue#117]
Expected behaviour:
![image](https://github.com/hedefalk/atom-vue/assets/68846168/31752361-d25f-4e85-8a8d-9450feb0ba71)
![image](https://github.com/hedefalk/atom-vue/assets/68846168/055745af-777a-4884-b308-40f07d8bdbac)

Actual behaviour:
![image](https://github.com/hedefalk/atom-vue/assets/68846168/4bada11d-c4af-414d-88b9-54ff6303729f)
![image](https://github.com/hedefalk/atom-vue/assets/68846168/75ec06c5-8192-4084-8104-ca41f7866de7)

**Comment by zhaolinlau** [comment]
@hedefalk I know that you are not maintaining this package any more, but I would like to request for your help to fix this issue.

**Comment by zhaolinlau** [comment]
I am using this package in [Pulsar](https://pulsar-edit.dev/) text editor(next generation of Atom text editor)

**Comment by hedefalk** [comment]
I cannot help you with this unfortunately, but see my comment on #118

**Comment by confused-Techie** [comment]
@zhaolinlau Looking into this issue, the behavior seems a little interesting.

Basically the underlining behavior you are seeing relies on a core package of Pulsar called [`bracket-matcher`](https://github.com/pulsar-edit/pulsar/tree/master/packages/bracket-matcher). Specifically this package uses some [fancy logic](https://github.com/pulsar-edit/pulsar/blob/master/packages/bracket-matcher/lib/tag-finder.js) to determine when any two parts of a text buffer are a pair of tags.

While, like you pointed out this isn't always correctly identified on any other tags within this package, other than `template`, the other tags in this package are **sometimes** correctly identified. Consider the below example:

![pulsar-bracket-matcher-example](https://github.com/hedefalk/atom-vue/assets/26921489/99e9ee13-019c-47bb-8199-3efb604c69e5)

This behavior seems determined by the Regex that `bracket-matcher` uses to determine the scopes of a pair of tags, which I'll add below:

```javascript
const TAG_SELECTOR_REGEX = /(\b|\.)(meta\.tag|punctuation\.definition\.tag)/;
```

From here you can see that in order for our tags to be properly considered as a pair, then they should begin with either `meta.tag` or `punctuation.definition.tag`.

Which in the case of things like `template` it is properly given the scope `meta.tag` but the other items like:

* `script`
* `style`

Are not being identified, even though those tags both seem to begin with `punctuation.definition.tag`. But those scopes are only applied to `<`, `>`, and `/>` which is why if the cursor is at the beginning or end of the generally non-identified tags then they will receive an underline. Meanwhile `template` receives the `meta.tag` scope for the entire range of text, ensuring it's always underlined properly.

All of this is to say, to fix the issue, we either need to make some bigger changes into how we scope the text within `<>` or I'm in talks with those over at Pulsar, if we instead believe that the functionality of `bracket-matcher` should be expanded to support this functionality.

**Comment by zhaolinlau** [comment]
@confused-Techie Alright, I'll wait for your future update.
