### ISSUE TITLE
support for <style lang="stylus">

### ISSUE THREAD

**Issue by collapsarzhang** [hedefalk/atom-vue#13]
I saw that you have it in the config, but somehow it's not working

**Comment by aidistan** [comment]
Everything works fine for me. Since `language-vue` does not highlight stylus code by itself, you may need to install `stylus` or `language-stylus` at first. 

If you still encounter this issue, please provide more information for us to fix it. Thanks!

**Comment by bemayr** [comment]
Hi there!

I did have the same problem until I changed `source.stylus.embedded.html` to `source.css.stylus.embedded.html`, because `stylus` includes `*.css.*` in contrary to `language-stylus`.
[stylus](https://github.com/devongovett/atom-stylus/blob/master/settings/language-stylus.cson) vs. [language-stylus](https://github.com/matthojo/language-stylus/blob/master/settings/language-stylus.cson)
As a temporary solution I have just edited `vue.cson` appropriately, but for updates a fix for this would be great!

**Comment by aidistan** [comment]
Hi @bemayr 

Actually, it is [this line](https://github.com/hedefalk/atom-vue/blob/master/grammars/vue.cson#L129) other than the pattern name that affects.

I'm sorry that I just tested the grammar with `language-stylus` but missed `stylus`. The upcoming version will support both of them.
