### ISSUE TITLE
config to allow custom file ending

### ISSUE THREAD

**Issue by thisconnect** [hedefalk/atom-vue#14]
As `.vue` files are almost valid HTML (with `<!doctype html>` and `<title>`).

Please allow to set a custom file extension such as `.html` or `.vue.html`, see also https://github.com/vuejs/vue-loader-example/issues/25

**Comment by aidistan** [comment]
Customizing file extensions in the webpack config is acceptable in your own project, since it only affects your local files. While file recognization in any language highlight package is a global thing and should avoid conflicts with other languages (thus `html` is not a good idea).

It's OK to add some extension aliases, such as `.html.vue` (better than `.vue.html` in my opinion).

**Comment by thisconnect** [comment]
Thanks for your reply, I need to find out how to configure extension aliases in atom..

**Comment by aidistan** [comment]
`.html.vue` is supported already, since it still ends with `.vue`. And if you wanna add some other aliases, try to modify the installed package directly:
- open the grammar file of `language-vue` package (~/.atom/packages/language-vue/grammars/vue.cson)
- change `fileTypes: [ "vue" ]` to `fileTypes: [ "vue", "vue.html" ]`
- reload Atom by `ctrl + alt + R`
- done

Note: package update will reset this temporal hacking.

**Comment by thisconnect** [comment]
Perfect, added "vue.html" reload, works! Thanks a lot!
