### ISSUE TITLE
Linter doesn't work

### ISSUE THREAD

**Issue by sunabozu** [hedefalk/atom-vue#16]
Hi.

Today I noticed eslint stopped working in tabs with opened `.vue` files. I'm pretty sure it worked before, and it still works for regular `.js`files. Perhaps it has something to do with 1.4.1 update, although I'm not sure what packages this problem related to.

**Comment by aidistan** [comment]
@sunabozu Compared to Atom's eslint interface packages, this repo is relative stable. I don't think here is the right place for your issue.

And if you really want us to help you, please provide more information about your environment, like:
- the version of your Atom
- the version of the eslint you currently use
- the eslint interface package you use and its version (**most important**)

**Comment by sunabozu** [comment]
As I mentioned above, eslint still works with plain js files, the problem occurs only with vue components. So I thought it has something to do with this package.

I have the latest versions of the mentioned packages: Atom 1.4.1, linter-eslint 6.0.0, base linter 1.11.3. Plus babel-eslint@4.1.6 (via npm).

I'm not quite sure what you mean by the interface package.

**Comment by aidistan** [comment]
@sunabozu 
1. I said "this package is relative stable", which means the issue you complained about (it worked before, it works in `.js` but failed in `.vue`) is more likely caused by the eslint interface package rather than `language-vue`. And the suggestion I gave only aims at helping you solve the issue ASAP.
2. `linter-eslint` you currently use is the **interface** package, which means it works as a bridge between Atom and eslint

---

This issue is most likely caused by following lines in [_linter-eslint/main.js_](https://github.com/AtomLinter/linter-eslint/blob/master/src/main.js#L69) :

``` js
const embeddedScope = 'source.js.embedded.html'
this.subscriptions.add(atom.config.observe('linter-eslint.lintHtmlFiles', lintHtmlFiles => {
  if (lintHtmlFiles) {
    this.scopes.push(embeddedScope)
  } else {
    if (this.scopes.indexOf(embeddedScope) !== -1) {
      this.scopes.splice(this.scopes.indexOf(embeddedScope), 1)
    }
  }
}))
```

The **solution** is to enable "Linter HTML Files" in the settings of `linter-eslint` and install `eslint-plugin-html`. (This works for me)

---

I had never used `ESLint` before and now I find it's awesome. Thx!

**Comment by sunabozu** [comment]
Your solution works for me too. Thanks!

I guess, the problem is solved now.

**Comment by sunabozu** [comment]
It seems like the problem still exists. And enabling the "Lint HTML Files" option doesn't help anymore. Linting works on the regular .js files though.

Atom 1.15.0,
eslint@3.18.0,
eslint-plugin-html@2.0.1

**Comment by mixn** [comment]
Since [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) has now [moved away](https://github.com/BenoitZugmeyer/eslint-plugin-html#linting-vue-files) from [https://github.com/BenoitZugmeyer/eslint-plugin-html](eslint-plugin-html), I wonder what the best/right way is, to get linting feedback for `.vue` files inside Atom…? 🤔

**Comment by aidistan** [comment]
Guess `eslint-plugin-vue` written by the vuejs community is a better choice.

**Comment by mikestopcontinues** [comment]
This topic merits reopening as this solution doesn't work with the `eslint-plugin-vue`, described by @mixn.

**Comment by jormar** [comment]
Hi. I'm having this problem. The previous solution did not work for me

**Comment by ianpaschal** [comment]
Indeed, this solution no longer works.

**Comment by LiamKlyneker** [comment]
hi! is any solution like this for Sublime Text 3? :'(

**Comment by aldencolerain** [comment]
Following these instructions got Atom linting .vue files for me:
https://github.com/vuejs/eslint-plugin-vue/issues/371#issuecomment-364652923
