### ISSUE TITLE
Atom freezes when opening vue-component with inline svg with inline styles of a certain length

### ISSUE THREAD

**Issue by tikiatua** [hedefalk/atom-vue#24]
Atom freezes often when trying to open slightly larger vue-component files. Package is up-to-date and was tested in Atom 1.8.0-beta3.

Any help would be greatly appreciated

**Comment by aidistan** [comment]
@tikiatua Never met this situation before. Would you attach a "slightly larger vue-component file" please?

**Comment by tikiatua** [comment]
Hi there, 

just had some time to investigate the issue. It seems to come down to an inline svg element with inline styles of a certain length.

``` html
<template>
    <svg width="10px" height="9px" viewBox="0 0 10 9" version="1.1" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:1.41421">
        <path d="M3.835,5.607l-1.839,-1.839l-1.215,1.214l3.089,3.089l0.607,-0.643l5.304,-5.625l-1.25,-1.178l-4.696,4.982Z" style="fill:#7ed321;"></path>
    </svg>
</template>
```

**Comment by aidistan** [comment]
@tikiatua 

This issue seems caused by [the complicated regexp used for `vue-directive`](https://github.com/hedefalk/atom-vue/blob/master/grammars/vue.cson#L527-L543). Any long attribute with lots '-' will freeze Atom, such as:

``` html
<template>
  <hodor hold-the-door="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;">
  </hodor>
</template>
```

I have simplified the regexp. Let's see how's it going.

Thanks for reporting this issue.

**Comment by tikiatua** [comment]
Awesome. The update fixed the problem.
