### ISSUE TITLE
syntax highlighting on functions

### ISSUE THREAD

**Issue by nerminba** [hedefalk/atom-vue#61]
Is it possible to achive this:

![](http://i.imgur.com/zw21ptZ.png)
![](http://i.imgur.com/gPvw3hB.png)

I belive that is in phpstorm, 

right now in my atom with this plugin it looks like this:
![](http://i.imgur.com/Q8wKQlx.png)
![](http://i.imgur.com/zxPOBa7.png)

**Comment by aidistan** [comment]
@nermamax It is possible to achive that and you could do it yourself. This package just delegate the syntax highlighting to your default HTML or Javascript highlight package.

I'm sure you will find better choices than the official ones, but I've no recommendations (since I'm OK with the defaults 😄). 

---

Close this issue due to the unrelatedness to this project.
