### ISSUE TITLE
Additional snippets via a PR

### ISSUE THREAD

**Issue by abea** [hedefalk/atom-vue#94]
Would you be interested in accepting a PR adding additional snippets? I'd use Sarah Drasner's VS Code extension as a guide on this given her deep experience developing with Vue.

https://github.com/sdras/vue-vscode-snippets/tree/master/snippets

**Comment by hedefalk** [comment]
@abea 

Sorry for not responding timely! 

At this point I'm not actively using or maintaining this project any longer. @aidistan has been the main maintainer for quite some time. @aidistan, do you still use and have time for this?

Personally I'm all open to anything and I guess the project needs active maintainers which I'm not so :)

**Comment by aidistan** [comment]
@abea  Yes, we would like to accept any additional snippets with general purpose and `sdras/vue-vscode-snippets` is a really good reference.

Since I'm not that into snippets, it would be better if you are interested in sending a PR.

---

@hedefalk Got your message from email and sorry for no response to issues and PRs. I was away from Vue projects for a while and now it's time to come back. I will try to close remained issues ASAP :smile:

**Comment by hedefalk** [comment]
@aidistan Great, thanks! Saw you had a big ticket bonanza! yey 👍

**Comment by abea** [comment]
Awesome. I'll plan to work on that soon!
