### ISSUE TITLE
Use this repo as sub for your snippets?

### ISSUE THREAD

**Issue by TriMoon** [hedefalk/atom-vue#98]
While searching for support in atom in respect to vue i noticed this package but also noticed it had almost no snippets defined, while searching for snippets i came along [Vuejs-snippets](https://github.com/CorentinAndre/Vuejs-snippets) which seems to concentrate on that aspect alone.
So would it be an idea for you guys to use that repo as a sub-module in your project to source-out the snippets part?

**Comment by aidistan** [comment]
Hi @TriMoon. Sorry for no snippets defined here, since I don't quite enjoy working with snippets.

Related topic has been discussed [here](#94) and please feel free to send a PR to implement this, while just make sure the license updated according to the one in [CorentinAndre/Vuejs-snippets](https://github.com/CorentinAndre/Vuejs-snippets).

**Comment by TriMoon** [comment]
Related topic is at #94 (Your link points back here) :wink:
